#! /usr/bin/env bash
export NEWT_COLORS='root=default,default window=black,black border=white,black shadow=default,default title=white,black label=white,black listbox=white,black'

foot -a foot.float nmtui
