#! /usr/bin/env bash
shopt -s nullglob

checked_move() {
    if ! [[ $1 -ef $2/${1##*/} ]]; then
        mv $1 $2
    fi
}

sort_dir() {
    age=$(( ($(date +%s) - $(stat -c %Y $1)) / 86400 ))

    if [[ $age -gt 120 ]]; then
        checked_move "$1" "/home/brayden/Documents/Coding/old"
    elif [[ $age -gt 30 ]]; then
        checked_move "$1" "/home/brayden/Documents/Coding/stale"
    else
        checked_move "$1" "/home/brayden/Documents/Coding/new"
    fi
}

for base_dir in /home/brayden/Documents/Coding/*; do
    for dir in $base_dir/*; do
        sort_dir $dir
    done
done
