#!/usr/bin/env zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(fd . ~/Documents/Coding/TypeScript ~/Documents/Coding/Rust ~/Documents/Coding/Java ~/Documents/Coding/Other ~/Documents/Coding/BigRepos --exact-depth 1 --type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

# tmux list-panes -s -F "#{session_name}:#{window_index}.#{pane_index}" | xargs -I{} sh -c 'tmux send-keys -t {} "C-!"'

tmux switch-client -t $selected_name

# tmux list-panes -s -F "#{session_name}:#{window_index}.#{pane_index}" | xargs -I{} sh -c 'tmux send-keys -t {} "C-#"'
