#!/usr/bin/env zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(fd . ~/Documents/Coding/hypr ~/Documents/Coding/TypeScript ~/Documents/Coding/Rust ~/Documents/Coding/Java ~/Documents/Coding/Other ~/Documents/Coding/BigRepos --exact-depth 1 --type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]] ; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
